import operator
from typing import Dict, Annotated, Optional, Literal
from pydantic import BaseModel, Field

from pydantic import field_validator

class ResearchState(BaseModel):
    ...
    user_topic: str = Field(
        default="",
        description="The topic or query user wants to research"
    )

    @field_validator("user_topic")
    @classmethod
    def topic_must_not_be_empty(cls, v):
        if not v.strip():
            raise ValueError("user_topic cannot be empty — please provide a research topic.")
        return v

    context: Optional[str] = Field(
    default=None,
    description="Joined text from retrieved chunks for the Analyzer."
)
    #planning phase
    reserach_plan:list[str] = Field(default_factory=list, 
    description="A structured topic or querie generated by the Planner.")
 

    #Search results
    web_results:Annotated[list[Dict], operator.add]= Field(
    default_factory=list,
    description="Search results collected from Tavily (contains snippets, titles, URLs)")

    research_papers:Annotated[list[Dict], operator.add] = Field(
    default_factory=list, 
    description="All search papers and metadata fetched from ArXiv")


    #RAG
    retrieved_chunk:list[str] = Field(
        default_factory=list, 
        description="Relevant text passages retrieved from the local vector DB / knowledge base.")


    #Analyzer & Verification
    analysis:Optional[str] = Field(None,
    description="The raw synthesized analysis produced by the Analyzer agent.")
   
    verified_analysis: Optional[str] = Field(
        None, 
        description="The fact-checked and verified version of the analysis."
    )
    
    #Output Genration
    markdown_report: Optional[str] = Field(
        None,
        description="The final polished report formatted in Markdown"
    )

    pdf_path: Optional[str] = Field(
        None, 
        description="Local path to the generated PDF available for user download."
    )
    
    #Human in the Loop
    apporoval_status: Optional[Literal["pending", "appoved", "revision_required", "rejected"]] = Field(
    default="pending",
    description="The current status of the apporval workflow."
    )
    
    feedback: Optional[str] = Field(
        None, 
        description="User instructions/revisions if they request changes to the report."
    )

    #System Orchestration
    workflow_status: str = Field(
        default="initialized",
        description="The current status of the graph (e.g., Planning, Searching, Analyzing, Generating Report, Completed"
    )
    error: Optional[str] = Field(
        default=None, 
        description="Error message if any error occurs."
    )

    class Config:
        """Pydantic model configuration."""
        use_enum_values = True
        arbitrary_types_allowed = True

























        